### PR TITLE
Fix a -Wincomplete-uni-patterns warning

### PR DESCRIPTION
**Pull request by ckoparkar**
This warning will soon be enabled by -Wall (See Trac #15656).

### CODE REVIEW

**Comment by ckoparkar** [comment]
The incomplete patterns:

1. [`readCreateProcess`](https://github.com/haskell/process/blob/master/System/Process.hs#L457)
2. [`readCreateProcessWithExitCode`](https://github.com/haskell/process/blob/master/System/Process.hs#L526)

**Comment by snoyberg** [comment]
Yes, I'd much prefer that to turning off this warning. Would you be able to update the PR?

**Comment by ckoparkar** [comment]
@snoyberg Yes, I realize that's what I should have done, instead of suppressing the warning. Should I use plain `error`, or would that break the semantics of other things which use `IOException`s ?

**Comment by snoyberg** [comment]
Using error should be fine.

**Comment by ckoparkar** [comment]
@snoyberg fixed it to  use `error`.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
