### PR TITLE
testsuite: Omit process005 in ghci way

### PR DESCRIPTION
**Pull request by bgamari**
See [GHC #16547](https://gitlab.haskell.org/ghc/ghc/issues/16547).

### CODE REVIEW

**Comment by RyanGlScott** [comment]
What is the reason for skipping this test? Is there a GHC issue that we can refer to?

**Comment by snoyberg** [comment]
I was about to merge, but just discovered that I no longer have commit access to this repo. I was not informed that I've been removed as the maintainer of this package, but I'm also unsure of who removed my access. In fact, I'm not even certain who to ask about this.

**Comment by RyanGlScott** [comment]
@snoyberg, that's rather strange... I just checked the project settings, and it looks like you have write access now. Can you confirm if you can push things on your end?

**Comment by snoyberg** [comment]
Looks like permissions were added back, thanks for pinging @RyanGlScott. Let's see if I can merge this...

**Pull request merged**
