### PR TITLE
#59 (binary versions of readProcess, etc.)

### PR DESCRIPTION
**Pull request by robjhen**
I have structured this pull request as 3 separate commits for ease of reviewing - see commit messages for details.

Notes:
- Tested on Debian GNU/Linux with both ghc 7.4.1 and ghc 7.10.2.
- Was unable to test on Windows as I do not have access to a Windows machine.
- I have not given an upper bound for the 'bytestring' package dependency in process.cabal: you may wish to add one. However I chose the lower bound (0.9.2) with some care: it is the lowest value compatible with the other package constraints, and it is also the version of bytestring that comes with ghc 7.4.1.

### CODE REVIEW

**Comment by robjhen** [comment]
The automated build failures appear to be because Hackage was down for maintenance at the time? The Travis build reported "cabal update failed 3 times" then "unknown package: HUnit". Is there a straightforward way to retry these builds?

**Comment by ggreif** [comment]
you can restart them in travis

**Comment by ggreif** [comment]
@robjhen I restarted the builds. `cabal` did well, `stack` not so.

**Comment by robjhen** [comment]
Okay, all done. The build failures with stack were due to a dependency on HUnit for a test suite added by me. I fixed this problem by changing the resolver in stack.yaml from ghc-7.10.2 to lts-5.14, and making some related changes in the .travis.yml script.

**Comment by snoyberg** [comment]
I'm concerned about such a large change, on a feature that was controversial to add to process in the first place. I'm also not sure what advantages are gained from copying so much code around instead of simply using `System.Process` exported identifiers in the binary module.

Some of the work here is straightforward and can be merged in, like changing the .hsc file extension and cleaning up language extensions. Can we start with a PR to just do that? There are then other breaking changes that may be worth doing, but need a little bit more exploration (CreateBinaryPipe caught my eye). After those are taken care of, we can circle back to considering the main functionality additions. But my preference would be for more focused code additions rather than large restructurings.

**Comment by robjhen** [comment]
Okay, agreed - it makes sense to approach this in smaller chunks. I'll make a new pull request for changing the .hsc extension.

**Pull request closed without merging**
