### PR TITLE
Move Haddock from ProcessHandle__ to ProcessHandle

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
I think this Haddock should be moved to the externally supported data definition.  Is that right?

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
(The diff looks like the definition has moved, but it's the same effect as moving the Haddock)

**Comment by tomjaguarpaw** [comment]
Pinging @snoyberg: I think this is a fairly straightforward change.

**Comment by snoyberg** [comment]
Sorry for the delay, I completely missed this. Thanks for the ping and the change.

**Comment by tomjaguarpaw** [comment]
You're welcome. Thanks for your maintainership of this great library!

**Pull request merged**
