### PR TITLE
Fix process tests on OpenBSD

### PR DESCRIPTION
**Pull request by blackgnezdo**

### CODE REVIEW

**Comment by snoyberg** [comment]
Since these are run by GHC's test suite and not the local one, @bgamari would you mind reviewing and signing off if you're happy with this change? Feel free to merge too if you'd like, or I can.

**Comment by blackgnezdo** [comment]
Ping for the next release?

**Review by snoyberg — APPROVED** [review]

**Comment by snoyberg** [comment]
Sorry, I thought I'd seen @bgamari sign off on this. I need to wait on his approval before merging.

**Comment by bgamari** [comment]
I'll try to test this in the GHC testsuite tomorrow.

**Comment by bgamari** [comment]
Indeed the GHC testsuite passes when built against this branch.

**Pull request merged**
