### PR TITLE
Allow base-4.15

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
I suspect that revising might not be a good idea in this case as WinIO sadly may result in previos versions  breaking (see #177).

**Comment by snoyberg** [comment]
Does that mean that this PR is essentially incomplete, and this commit would not be safe for release to Hackage?

**Comment by bgamari** [comment]
That is correct.

**Comment by snoyberg** [comment]
Understood, thanks.

**Comment by bgamari** [comment]
Also, just to clarify, we do hope to get WinIO this week.

**Comment by Mistuke** [comment]
process's own package bounds aren't much of an issue, process will compile with or without WINIO. The difficulty here is that GHC 8.12 itself in order to use WINIO requires at least the process it ships with.

I think the only way to solve that is for libGHC itself to have a tight version bound on process versions. But process itself can be as liberal as it wants unless I'm mistaken?

**Pull request merged**
