### PR TITLE
Bump version to 1.6.8.1

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
@snoyberg to prevent confusion I have pushed this branch which bumps the version number. I will release 8.10.1 with this commit. Feel free to push to Hackage when you get a chance. Apologies for missing the warnings that prompted this earlier.

**Comment by snoyberg** [comment]
No worries, uploaded to Hackage.

**Comment by bgamari** [comment]
Thanks! Good luck fighting off the COVID zombies.

**Comment by snoyberg** [comment]
Thanks! Head shots are the key.

**Pull request merged**
