### PR TITLE
Various fixes for `posix_spawn` refactoring

### LINKED ISSUE #210: GHC build/testsuite failures with process 1.6.13.0
There are a couple of warnings with the new refactor in #208  (promoted to errors with `-Werror`):

```
libraries/process/cbits/posix/posix_spawn.c:68:1: error:
     error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
   |
68 | }
   | ^
cc1: all warnings being treated as errors
`cc' failed in phase `C Compiler'. (Exit code: 1)
libraries/process/ghc.mk:4: recipe for target 'libraries/process/dist-install/build/cbits/posix/posix_spawn.o' failed
make[1]: *** [libraries/process/dist-install/build/cbits/posix/posix_spawn.o] Error 1
make[1]: *** Waiting for unfinished jobs....
libraries/process/cbits/posix/find_executable.c: In function ‘find_executable’:
libraries/process/cbits/posix/find_executable.c:31:48: error:
     error: ‘__s’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
             const int tmp_len = filename_len + 1 + strlen(path) + 1;
                                                    ^~~~~~~~~~~~
   |
31 |         const int tmp_len = filename_len + 1 + strlen(path) + 1;
   |                                                ^
libraries/process/cbits/posix/find_executable.c:26:14: error:
     note: ‘__s’ was declared here
     static char *find_in_search_path(char *search_path, const char *filename) {
                  ^~~~~~~~~~~~~~~~~~~
   |
26 | static char *find_in_search_path(char *search_path, const char *filename) {
   |              ^
cc1: all warnings being treated as errors
`cc' failed in phase `C Compiler'. (Exit code: 1)
libraries/process/cbits/posix/fork_exec.c: In function ‘do_spawn_fork’:
libraries/process/cbits/posix/fork_exec.c:222:19: error:
     error: suggest parentheses around comparison in operand of ‘&’ [-Werror=parentheses]
             if (flags & RESET_INT_QUIT_HANDLERS != 0) {
                       ^
    |
222 |         if (flags & RESET_INT_QUIT_HANDLERS != 0) {
    |                   ^
libraries/process/cbits/posix/fork_exec.c: In function ‘setup_std_handle_fork’:
libraries/process/cbits/posix/fork_exec.c:89:1: error:
     error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
   |
89 | }
   | ^
cc1: all warnings being treated as errors
```

In addition, there are two testsuite failures once `-Werror` is no longer in effect.

`T3994` - `waitForProcess` now fails with `UserInterrupt` when it is expected to complete without failures

```
Wrong exit code for T3994(threaded1)(expected 0 , actual 130 )
Stdout ( T3994 ):
start
*** unexpected failure for T3994(threaded1)
```

```haskell
main :: IO ()
main = do (_,Just hout,_,p) <- createProcess (proc "./T3994app" ["start", "10000"])
                            { std_out = CreatePipe, create_group = True }
          start <- hGetLine hout
          putStrLn start
          interruptProcessGroupOf p
          t <- myThreadId
               -- timeout
          forkIO $ do
            threadDelay 5000000
            putStrLn "Interrupting a Running Process Failed"
            hFlush stdout
            killThread t
          waitForProcess p
       -- ^^^^^^^^^^^^^^^ this fails with `UserInterrupt`
          putStrLn "end"
          return ()
```

`process010` fails with a benign error message change which can probably be accepted.

```
+++ "/builds/ghc/ghc/tmp/ghctest-3wgma_aq/test   spaces/libraries/process/tests/process010.run/process010.run.stdout.normalised"	2021-07-12 19:36:34.037437016 +0000
@@ -1,4 +1,4 @@
 ExitSuccess
 ExitFailure 1
-Exc: /non/existent: rawSystem: posix_exec: illegal operation (Inappropriate ioctl for device)
+Exc: /non/existent: rawSystem: posix_exec: does not exist (No such file or directory)
 Done
```

In general, we need a better story for the GHC tests included in `process`. Ideally we would be able to run them in `process` CI as well.

Unfortunately, this means there will need to be another release soon.

/cc @bgamari

### PR DESCRIPTION
**Pull request by bgamari**
Sadly, the refactor in #208 had a few issues which my earlier testing hadn't uncovered:

 * the `posix_spawn` path didn't correctly handle the case where the platform does not support `POSIX_SPAWN_SETPGROUP`
 * some compilers warned of missing (but in principle unreachable) cases, breaking the `-Werror` build in some cases
 * `fork_exec`'s `setup_std_handle_fork` failed to return a value in some cases
 * the `configure` script failed to declare its dependency on `<spawn.h>`, causing it to fail to find `posix_spawn` in some cases
 * GCC 6.3 threw spurious warnings in `find_executable.c`, breaking the `-Werror` build
 * the output expected by the GHC testsuite had a spurious platform dependence due to the new `posix_spawn` implementation

I have fixed all of these and tested on Linux, Darwin, and FreeBSD.

Fixes #210.

### CODE REVIEW

**Comment by snoyberg** [comment]
Awesome, thanks! Want me to make a release?

**Comment by bgamari** [comment]
Thanks @snoyberg! Let's hold off on the release just a tad longer; I've seen something in further testing that has me a bit concerned.

**Comment by bgamari** [comment]
A brief update: I am increasingly certain that the issue that I mentioned earlier is actually a (rather nasty) GHC bug (namely https://gitlab.haskell.org/ghc/ghc/-/issues/20137) but it would likely still be prudent to wait until we have a fix and verification before doing a release. I'm hopeful that we'll have a fix tomorrow..

**Comment by bgamari** [comment]
Alright, at this point I have eliminated this patch as the source for any of the issues we have seen in `process` in CI. Feel free to cut a release when you have time, @snoyberg. Cheers!

**Comment by snoyberg** [comment]
Upload complete!

**Pull request merged**
