### PR TITLE
Add stopDelegateControlC for MinGW32

### PR DESCRIPTION
**Pull request by takenobu-hs**
Hi,

I would like to thank a lot of effort.
I added stopDelegateControlC function for MinGW32.
Please check:-)

### CODE REVIEW

**Comment by snoyberg** [comment]
I'm afraid I don't understand the purpose of this patch. Can you describe what the problem is that you are trying to solve, and how this solves it?

**Comment by hvr** [comment]
@snoyberg, @thoughtpolice will chime in soon; this is about https://mail.haskell.org/pipermail/ghc-devs/2015-February/008347.html

**Comment by thoughtpolice** [comment]
3b5804ebe54c672146994cfc525d45280650043e introduces the use of `stopDelegateControlC` inside `Process.hsc`. This lives in `Internals.hs`, which has an export list that always exports this function. But the implementation is `#ifdef`'d between Unix and Windows. This causes a build failure on Windows where `stopDelegateControlC` was not defined, which this patch fixes (it should be a no-op on Windows). I believe Takenobu's patch is the easiest way to fix this.

**Comment by snoyberg** [comment]
Thanks for the clarification, that makes sense.

@takenobu-hs Would you be able to update this PR to include a short explanation in the code as to why we have that no-op function? It could even just be a link pointing to this discussion.

**Comment by takenobu-hs** [comment]
Sorry less information and thank you for the detailed instructions.

I updated the commit message and re-sent a PR for issue #21
If I mistake something, please teach again.

Thank you.

**Comment by snoyberg** [comment]
I was actually hoping for the comments to be added in the code, not the commit message, so that in the future, when someone is reading through the codebase, they can understand why there's a no-op function present. Can you amend in that way?

**Comment by takenobu-hs** [comment]
Oh, I understood.
Thank you for repeatedly teach me.

I added a comment in the code.

How about this?

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
